# -*- coding: utf-8 -*-
"""
Created on Fri Mar 23 13:08:37 2012

@author: tricc
"""
#constant error code definition for FPGA update

# Error Code Start 
CB_OK								=0

CB_FS_OPEN_FILE_ERROR				=-1
CB_FS_CLOSE_FILE_ERROR				=-2
CB_FS_SIZE_EOF_NOT_FOUND			=-3
CB_FS_READ_ERROR					=-4

CB_BB_OPEN_ERROR_OPEN_PORT			=-5
CB_BB_OPEN_VERSION_INCOMPATIBLE		=-6
CB_BB_OPEN_DRIVER_INCOMPATIBLE		=-7
CB_BB_OPEN_DEVICEIOCONTROL_FAIL		=-8
CB_BB_CLOSE_BYTEBLASTER_NOT_OPEN	=-9
CB_BB_FLUSH_ERROR					=-10
CB_BB_VERIFY_BYTEBLASTER_NOT_FOUND	=-11
CB_BB_LPTREAD_ERROR					=-12
CB_BB_LPTWRITE_ERROR				=-13

CB_PS_CONF_NSTATUS_LOW				=-14
CB_PS_CONF_CONFDONE_LOW				=-15
CB_PS_INIT_NSTATUS_LOW				=-16
CB_PS_INIT_CONFDONE_LOW				=-17

CB_AS_VERIFY_FAIL					=-18
CB_AS_UNSUPPORTED_DEVICE			=-19 
CB_AS_WRONG_RPD_FILE				=-20

CB_INVALID_NUMBER_OF_ARGUMENTS		=-21
CB_INVALID_COMMAND					=-22
CB_INVALID_EPCS_DENSITY				=-23

# Error Code END  